# XplainTDA

In [1]:
import scanpy as sc
from XplainTDA import XplainTDA

❌ CUDA not available. Using CPU.

In [2]:
adata=sc.read_h5ad("Datasets/PBMC/CM/PBMC_GEX_Def.h5ad")
adata

AnnData object with n_obs × n_vars = 5639 × 2752
    obs: 'RNA_celltype', 'Raw_CellType', 'CellType', 'n_features', 'log_n_features', 'n_counts', 'log_n_counts', 'n_genes_by_counts', 'total_counts', 'total_counts_MT', 'pct_counts_MT', 'doublet_score', 'predicted_doublet', 'passes_filter'
    var: 'gene_ids', 'feature_types', 'n_cells', 'log_n_cells', 'MT', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'passes_filter', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'hvg', 'scrublet'
    obsm: 'X_GRAE'

In [3]:
adata_red=adata[:100, :30].copy()
adata_red

AnnData object with n_obs × n_vars = 100 × 30
    obs: 'RNA_celltype', 'Raw_CellType', 'CellType', 'n_features', 'log_n_features', 'n_counts', 'log_n_counts', 'n_genes_by_counts', 'total_counts', 'total_counts_MT', 'pct_counts_MT', 'doublet_score', 'predicted_doublet', 'passes_filter'
    var: 'gene_ids', 'feature_types', 'n_cells', 'log_n_cells', 'MT', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'passes_filter', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'hvg', 'scrublet'
    obsm: 'X_GRAE'

In [4]:
tda = XplainTDA(adata_red, embedding_key="X_GRAE")
tda.fit()
tda.save("tda.joblib")

--------------I AM USING GUDHI--------------

In [5]:
tda2 = XplainTDA.load("tda.joblib")
tda2

# Local_XplainTDA

In [1]:
import numpy as np
import scanpy as sc

from XplainTDA import XplainTDA
from Local_XplainTDA import Local_XplainTDA

2026-06-04 17:57:42,359 - INFO - ❌ CUDA not available. Using CPU.

Module base_dataset has been imported DEVICE --> cpu

In [2]:
adata=sc.read_h5ad("../Topology/Datasets/PBMC/CM/PBMC_GEX_Def.h5ad")
adata

AnnData object with n_obs × n_vars = 6169 × 27607
    obs: 'RNA_celltype', 'Raw_CellType', 'CellType', 'n_features', 'log_n_features', 'n_counts', 'log_n_counts', 'mt_frac', 'ribofrac', 'passes_filter', 'doublet_score', 'predicted_doublet'
    var: 'gene_ids', 'feature_types', 'n_cells', 'log_n_cells', 'passes_filter', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'hvg', 'scrublet'
    layers: 'counts'

In [3]:
adata_red=adata[:100, :30].copy()
adata_red

AnnData object with n_obs × n_vars = 100 × 30
    obs: 'RNA_celltype', 'Raw_CellType', 'CellType', 'n_features', 'log_n_features', 'n_counts', 'log_n_counts', 'mt_frac', 'ribofrac', 'passes_filter', 'doublet_score', 'predicted_doublet'
    var: 'gene_ids', 'feature_types', 'n_cells', 'log_n_cells', 'passes_filter', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'hvg', 'scrublet'
    layers: 'counts'

In [4]:
tda = XplainTDA(adata_red, embedder="PCA")
tda.fit()
tda.save("tda.joblib")

In [5]:
tda = XplainTDA.load("tda.joblib")
tda.adata=adata_red
tda.X=adata_red.X

In [6]:
local = Local_XplainTDA(tda)

In [7]:
df=local.importance_all_homologies()

Launching 1 jobs | H0 | 5 features Thu, 04 Jun 2026 17:57:52
Done H0 feature 49 | 100 cells Thu, 04 Jun 2026 17:58:03
Done H0 feature 48 | 100 cells Thu, 04 Jun 2026 17:58:15
Done H0 feature 47 | 99 cells Thu, 04 Jun 2026 17:58:26
Done H0 feature 46 | 89 cells Thu, 04 Jun 2026 17:58:37
Done H0 feature 45 | 89 cells Thu, 04 Jun 2026 17:58:49
Launching 1 jobs | H1 | 1 features Thu, 04 Jun 2026 17:58:49
Done H1 feature 5 | 59 cells Thu, 04 Jun 2026 17:59:00
Launching 1 jobs | H2 | 1 features Thu, 04 Jun 2026 17:59:00
Done H2 feature 0 | 70 cells Thu, 04 Jun 2026 17:59:12

In [8]:
local.save("Local_explainer.joblib")

In [9]:
df.to_csv("Local_expl.tsv.gz", sep="\t", compression="gzip")

In [10]:
df

,homology_dim,feature_id,feature_persistence,rank_within_feature,gene_idx,gene,score
0,0,49,1.814767,1,11,NOC2L,0.642721
1,0,49,1.814767,2,26,SDF4,0.604803
2,0,49,1.814767,3,29,UBE2J2,0.497294
3,0,49,1.814767,4,0,LOC105378947,0.441908
4,0,49,1.814767,5,4,FAM87B,0.441908
...,...,...,...,...,...,...,...
205,2,0,0.107898,26,22,TTLL10-AS1,0.000000
206,2,0,0.107898,27,21,LINC01342,0.000000
207,2,0,0.107898,28,20,LOC124903820,0.000000
208,2,0,0.107898,29,24,TNFRSF18,0.000000
209,2,0,0.107898,30,28,C1QTNF12,0.000000

# Global_XplainTDA

In [1]:
import numpy as np
import scanpy as sc

from XplainTDA import XplainTDA
from Global_XplainTDA import Global_XplainTDA

2026-06-05 10:17:39,304 - INFO - ❌ CUDA not available. Using CPU.

Module base_dataset has been imported DEVICE --> cpu

KeyboardInterrupt

In [ ]:
adata=sc.read_h5ad("../Topology/Datasets/PBMC/CM/PBMC_GEX_Def.h5ad")
adata

In [ ]:
adata_red=adata[:100, :70].copy()
adata_red

In [ ]:
#tda = XplainTDA(adata_red, embedder="PCA")
#tda.fit()
#tda.save("tda.joblib")

In [ ]:
tda = XplainTDA.load("tda.joblib")
tda.adata=adata_red
tda.X=adata_red.X

In [6]:
global_ = Global_XplainTDA(tda)

In [7]:
df=global_.importance_all_homologies()

Launching 1 jobs | genes=30 | dims=[0, 1, 2] Fri, 05 Jun 2026 09:02:58
Done gene LOC105378947 (0) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:02:59
Done gene LOC101928626 (1) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:02:59
Done gene LOC100288069 (2) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:00
Done gene LINC01409 (3) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:01
Done gene FAM87B (4) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:01
Done gene LINC00115 (5) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:02
Done gene LINC01128 (6) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:02
Done gene LOC107984850 (7) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:03
Done gene FAM41C (8) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:04
Done gene LOC124905686 (9) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:04
Done gene SAMD11 (10) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:05
Done gene NOC2L (11) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:06
Done gene KLHL17 (12) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:06
Done gene PLEKHN1 (13) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:07
Done gene HES4 (14) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:07
Done gene AGRN (15) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:08
Done gene LOC100288175 (16) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:09
Done gene LOC105378948 (17) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:09
Done gene RNF223 (18) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:10
Done gene C1orf159 (19) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:11
Done gene LOC124903820 (20) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:11
Done gene LINC01342 (21) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:12
Done gene TTLL10-AS1 (22) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:12
Done gene TTLL10 (23) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:13
Done gene TNFRSF18 (24) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:14
Done gene TNFRSF4 (25) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:14
Done gene SDF4 (26) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:15
Done gene B3GALT6 (27) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:15
Done gene C1QTNF12 (28) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:16
Done gene UBE2J2 (29) | dims=[0, 1, 2] Fri, 05 Jun 2026 09:03:17

In [8]:
df

,homology_dim,gene_idx,gene,distance_metric,score,approximation,approximation_note,rank
0,0,29,UBE2J2,bottleneck,0.367023,False,,1
1,0,11,NOC2L,bottleneck,0.364428,False,,2
2,0,26,SDF4,bottleneck,0.297377,False,,3
3,0,27,B3GALT6,bottleneck,0.125144,False,,4
4,0,19,C1orf159,bottleneck,0.112561,False,,5
...,...,...,...,...,...,...,...,...
85,2,21,LINC01342,bottleneck,0.000000,False,,2
86,2,22,TTLL10-AS1,bottleneck,0.000000,False,,2
87,2,23,TTLL10,bottleneck,0.000000,False,,2
88,2,24,TNFRSF18,bottleneck,0.000000,False,,2
89,2,28,C1QTNF12,bottleneck,0.000000,False,,2

In [9]:
global_.save("Global_explainer.joblib")

In [10]:
df.to_csv("Global_expl.tsv.gz", sep="\t", compression="gzip")

# StratifiedXplainTDA

In [1]:
import numpy as np
import pandas as pd
import scanpy as sc

from Stratified_XplainTDA import StratifiedXplainTDA

2026-06-05 11:14:01,364 - INFO - ❌ CUDA not available. Using CPU.

Module base_dataset has been imported DEVICE --> cpu

In [2]:
adata=sc.read_h5ad("../Topology/Datasets/PBMC/CM/PBMC_GEX_Def.h5ad")
adata

AnnData object with n_obs × n_vars = 6169 × 27607
    obs: 'RNA_celltype', 'Raw_CellType', 'CellType', 'n_features', 'log_n_features', 'n_counts', 'log_n_counts', 'mt_frac', 'ribofrac', 'passes_filter', 'doublet_score', 'predicted_doublet'
    var: 'gene_ids', 'feature_types', 'n_cells', 'log_n_cells', 'passes_filter', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'hvg', 'scrublet'
    layers: 'counts'

In [4]:
adata_red=adata[:100, :70].copy()
adata_red

AnnData object with n_obs × n_vars = 100 × 70
    obs: 'RNA_celltype', 'Raw_CellType', 'CellType', 'n_features', 'log_n_features', 'n_counts', 'log_n_counts', 'mt_frac', 'ribofrac', 'passes_filter', 'doublet_score', 'predicted_doublet'
    var: 'gene_ids', 'feature_types', 'n_cells', 'log_n_cells', 'passes_filter', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'hvg', 'scrublet'
    layers: 'counts'

In [5]:
adata_red.obs.CellType.value_counts()

CellType
Monocytes          29
T_CD4_memory       21
B_memory           13
T_CD4_naïve        10
T_CD8_activated     9
T_CD8_naive         8
B_naive             4
NK                  3
DCp                 2
T_MAIT              1
Name: count, dtype: int64

In [7]:
# -----------------------------
# 2. Build stratified runner
# -----------------------------
runner = StratifiedXplainTDA(adata_red, groupby="CellType", min_cells=20, outdir="Datasets/PBMC/XplainTDA/GEX")
runner

In [8]:
# -----------------------------
# 3. Local explanation
#    genes=None -> all genes
#    dims=None  -> all homologies from each group-specific TDA
# -----------------------------
local_res = runner.local_expl()

============================================================
Start local XplainTDA for T_CD8_naive Fri, 05 Jun 2026 11:14:40
============================================================

2026-06-05 11:14:40,616 - INFO - Fitting manifold learning method...

Calculating PHATE...
  Running PHATE on 85 observations and 70 variables.
  Calculating graph and diffusion operator...
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...

/home/gabriele/miniconda3/envs/tda/lib/python3.10/site-packages/graphtools/graphs.py:810: RuntimeWarning: Detected zero distance between 45 pairs of samples. Consider removing duplicates to avoid errors in downstream processing.
  warnings.warn(

    Calculated affinities in 0.84 seconds.
  Calculated graph and diffusion operator in 0.92 seconds.
  Calculating optimal t...
    Automatically selected t = 14
  Calculating diffusion potential...
  Calculating metric MDS...
    SGD-MDS may not have converged: stress changed by -2.1% in final iterations. Consider increasing n_iter or adjusting learning_rate.
  Calculated metric MDS in 0.05 seconds.
Calculated PHATE in 0.99 seconds.

/home/gabriele/miniconda3/envs/tda/lib/python3.10/site-packages/graphtools/graphs.py:505: RuntimeWarning: divide by zero encountered in divide
  scaled = distances_i / bw
/home/gabriele/miniconda3/envs/tda/lib/python3.10/site-packages/graphtools/graphs.py:505: RuntimeWarning: invalid value encountered in divide
  scaled = distances_i / bw
/home/gabriele/miniconda3/envs/tda/lib/python3.10/site-packages/graphtools/graphs.py:540: RuntimeWarning: invalid value encountered in divide
  scaled = distances_i / bw
2026-06-05 11:14:41,608 - INFO - Fitting encoder & decoder...
2026-06-05 11:14:42,418 - INFO - Epoch 10...
2026-06-05 11:14:42,522 - INFO - Epoch 20...
2026-06-05 11:14:42,611 - INFO - Epoch 30...
2026-06-05 11:14:42,693 - INFO - Epoch 40...
2026-06-05 11:14:42,779 - INFO - Epoch 50...
2026-06-05 11:14:42,812 - INFO - Model has been early stopped at epoch 52

Skipping T_CD8_naive: n_cells=8 < min_cells=20
============================================================
Start local XplainTDA for T_CD8_activated Fri, 05 Jun 2026 11:14:43
============================================================
Skipping T_CD8_activated: n_cells=9 < min_cells=20
============================================================
Start local XplainTDA for T_CD4_naïve Fri, 05 Jun 2026 11:14:43
============================================================
Skipping T_CD4_naïve: n_cells=10 < min_cells=20
============================================================
Start local XplainTDA for B_memory Fri, 05 Jun 2026 11:14:43
============================================================
Skipping B_memory: n_cells=13 < min_cells=20
============================================================
Start local XplainTDA for Monocytes Fri, 05 Jun 2026 11:14:43
============================================================
Fitting PH for Monocytes | cells=29 | n_neighbors=29 Fri, 05 Jun 2026 11:14:43
Launching 8 jobs | H0 | 3 features Fri, 05 Jun 2026 11:14:43
Done H0 feature 26 | 29 cells Fri, 05 Jun 2026 11:14:47
Done H0 feature 24 | 28 cells Fri, 05 Jun 2026 11:14:47
Done H0 feature 25 | 29 cells Fri, 05 Jun 2026 11:14:47
Launching 8 jobs | H1 | 1 features Fri, 05 Jun 2026 11:14:47
Done H1 feature 0 | 3 cells Fri, 05 Jun 2026 11:14:49
============================================================
Start local XplainTDA for B_naive Fri, 05 Jun 2026 11:14:49
============================================================
Skipping B_naive: n_cells=4 < min_cells=20
============================================================
Start local XplainTDA for T_CD4_memory Fri, 05 Jun 2026 11:14:49
============================================================
Fitting PH for T_CD4_memory | cells=21 | n_neighbors=21 Fri, 05 Jun 2026 11:14:49
Launching 8 jobs | H0 | 3 features Fri, 05 Jun 2026 11:14:49
Done H0 feature 20 | 21 cells Fri, 05 Jun 2026 11:14:52
Done H0 feature 18 | 15 cells Fri, 05 Jun 2026 11:14:52
Done H0 feature 19 | 21 cells Fri, 05 Jun 2026 11:14:52
Launching 8 jobs | H1 | 1 features Fri, 05 Jun 2026 11:14:52
Done H1 feature 0 | 5 cells Fri, 05 Jun 2026 11:14:53
============================================================
Start local XplainTDA for T_MAIT Fri, 05 Jun 2026 11:14:53
============================================================
Skipping T_MAIT: n_cells=1 < min_cells=20
============================================================
Start local XplainTDA for NK Fri, 05 Jun 2026 11:14:53
============================================================
Skipping NK: n_cells=3 < min_cells=20
============================================================
Start local XplainTDA for DCp Fri, 05 Jun 2026 11:14:53
============================================================
Skipping DCp: n_cells=2 < min_cells=20

In [9]:
# -----------------------------
# 4. Global explanation
#    genes=None -> all genes
#    dims=None  -> all homologies from each group-specific TDA
# -----------------------------
global_res = runner.global_expl()

============================================================
Start global XplainTDA for T_CD8_naive Fri, 05 Jun 2026 11:14:53
============================================================
Skipping T_CD8_naive: n_cells=8 < min_cells=20
============================================================
Start global XplainTDA for T_CD8_activated Fri, 05 Jun 2026 11:14:53
============================================================
Skipping T_CD8_activated: n_cells=9 < min_cells=20
============================================================
Start global XplainTDA for T_CD4_naïve Fri, 05 Jun 2026 11:14:53
============================================================
Skipping T_CD4_naïve: n_cells=10 < min_cells=20
============================================================
Start global XplainTDA for B_memory Fri, 05 Jun 2026 11:14:53
============================================================
Skipping B_memory: n_cells=13 < min_cells=20
============================================================
Start global XplainTDA for Monocytes Fri, 05 Jun 2026 11:14:53
============================================================
Launching 8 jobs | genes=70 | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LOC100288069 (2) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LINC00115 (5) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LOC105378947 (0) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LOC101928626 (1) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LINC01409 (3) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene FAM87B (4) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LINC01128 (6) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LOC107984850 (7) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene FAM41C (8) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene SAMD11 (10) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene PLEKHN1 (13) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene KLHL17 (12) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LOC124905686 (9) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene AGRN (15) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene NOC2L (11) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene HES4 (14) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LOC100288175 (16) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:53
Done gene LINC01342 (21) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene TNFRSF18 (24) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene TTLL10 (23) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene LOC124903820 (20) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene LOC105378948 (17) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene C1orf159 (19) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene TTLL10-AS1 (22) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene RNF223 (18) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene UBE2J2 (29) | dims=[0, 1, 2]Done gene SCNN1D (30) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene ACAP3 (31) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene B3GALT6 (27) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
 Done gene C1QTNF12 (28) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Fri, 05 Jun 2026 11:14:54
Done gene TNFRSF4 (25) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene SDF4 (26) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene PUSL1 (32) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene DVL1 (36) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene MXRA8 (37) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene TAS1R3 (35) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene AURKAIP1 (38) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene CCNL2 (39) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene INTS11 (33) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene MRPL20-AS1 (40) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene CPTP (34) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene ATAD3B (47) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene VWA1 (45) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene ATAD3A (48) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene ANKRD65 (43) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene ATAD3C (46) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene TMEM88B (44) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene MRPL20-DT (42) | dims=[0, 1, 2] Done gene MRPL20 (41) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Fri, 05 Jun 2026 11:14:54
Done gene LOC105378586 (52) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene SSU72 (50) | dims=[0, 1, 2]Done gene SLC35E2B (55) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
 Fri, 05 Jun 2026 11:14:54
Done gene TMEM240 (49) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene MMP23A (56) | dims=[0, 1, 2]Done gene MIB2 (53) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
 Fri, 05 Jun 2026 11:14:54
Done gene FNDC10 (51) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene MMP23B (54) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene CALML6 (61) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene SLC35E2A (57) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene LOC105378589 (64) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene CFAP74 (63) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene NADK (59) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene TMEM52 (62) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene LOC112268218 (58) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene GNB1-DT (60) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:54
Done gene LOC105378590 (66) | dims=[0, 1, 2]Done gene PRKCZ (67) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene GABRD (65) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
 Fri, 05 Jun 2026 11:14:55
Done gene FAAP20 (69) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene PRKCZ-AS1 (68) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
============================================================
Start global XplainTDA for B_naive Fri, 05 Jun 2026 11:14:55
============================================================
Skipping B_naive: n_cells=4 < min_cells=20
============================================================
Start global XplainTDA for T_CD4_memory Fri, 05 Jun 2026 11:14:55
============================================================
Launching 8 jobs | genes=70 | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC107984850 (7) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LINC00115 (5) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LINC01409 (3) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC105378947 (0) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC101928626 (1) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC100288069 (2) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LINC01128 (6) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene FAM87B (4) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene NOC2L (11) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene FAM41C (8) | dims=[0, 1, 2]Done gene PLEKHN1 (13) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
 Fri, 05 Jun 2026 11:14:55
Done gene HES4 (14) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene SAMD11 (10) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC124905686 (9) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene AGRN (15) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene KLHL17 (12) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC100288175 (16) | dims=[0, 1, 2]Done gene TTLL10 (23) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
 Fri, 05 Jun 2026 11:14:55
Done gene C1orf159 (19) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene TTLL10-AS1 (22) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC105378948 (17) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene RNF223 (18) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LINC01342 (21) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC124903820 (20) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene ACAP3 (31) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene UBE2J2 (29) | dims=[0, 1, 2]Done gene PUSL1 (32) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene B3GALT6 (27) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene TNFRSF4 (25) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
 Fri, 05 Jun 2026 11:14:55
Done gene SDF4 (26) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene SCNN1D (30) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene C1QTNF12 (28) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene TNFRSF18 (24) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene INTS11 (33) | dims=[0, 1, 2]Done gene DVL1 (36) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene AURKAIP1 (38) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene CPTP (34) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene TAS1R3 (35) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene MRPL20-AS1 (40) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
 Fri, 05 Jun 2026 11:14:55
Done gene CCNL2 (39) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene MXRA8 (37) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene MRPL20-DT (42) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene MRPL20 (41) | dims=[0, 1, 2]Done gene ATAD3A (48) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
 Fri, 05 Jun 2026 11:14:55
Done gene VWA1 (45) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene ATAD3C (46) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene ANKRD65 (43) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene ATAD3B (47) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene TMEM88B (44) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene MIB2 (53) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene SLC35E2B (55) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene FNDC10 (51) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC105378586 (52) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene MMP23B (54) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene TMEM240 (49) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene SSU72 (50) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene MMP23A (56) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene LOC112268218 (58) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene SLC35E2A (57) | dims=[0, 1, 2]Done gene NADK (59) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
 Fri, 05 Jun 2026 11:14:55
Done gene LOC105378589 (64) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene CFAP74 (63) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene TMEM52 (62) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:55
Done gene GNB1-DT (60) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:56
Done gene GABRD (65) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:56
Done gene LOC105378590 (66) | dims=[0, 1, 2]Done gene CALML6 (61) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:56
 Fri, 05 Jun 2026 11:14:56
Done gene PRKCZ-AS1 (68) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:56
Done gene FAAP20 (69) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:56
Done gene PRKCZ (67) | dims=[0, 1, 2] Fri, 05 Jun 2026 11:14:56
============================================================
Start global XplainTDA for T_MAIT Fri, 05 Jun 2026 11:14:56
============================================================
Skipping T_MAIT: n_cells=1 < min_cells=20
============================================================
Start global XplainTDA for NK Fri, 05 Jun 2026 11:14:56
============================================================
Skipping NK: n_cells=3 < min_cells=20
============================================================
Start global XplainTDA for DCp Fri, 05 Jun 2026 11:14:56
============================================================
Skipping DCp: n_cells=2 < min_cells=20

In [10]:
global_res

,group,n_cells,n_neighbors,method,homology_dim,gene_idx,gene,distance_metric,score,approximation,approximation_note,rank
0,Monocytes,29,29,global,0,59,NADK,bottleneck,0.041737,False,,1
1,Monocytes,29,29,global,0,33,INTS11,bottleneck,0.032087,False,,2
2,Monocytes,29,29,global,0,39,CCNL2,bottleneck,0.028031,False,,3
3,Monocytes,29,29,global,0,11,NOC2L,bottleneck,0.024177,False,,4
4,Monocytes,29,29,global,0,19,C1orf159,bottleneck,0.015360,False,,5
...,...,...,...,...,...,...,...,...,...,...,...,...
415,T_CD4_memory,21,21,global,2,65,GABRD,bottleneck,0.000000,False,,1
416,T_CD4_memory,21,21,global,2,66,LOC105378590,bottleneck,0.000000,False,,1
417,T_CD4_memory,21,21,global,2,67,PRKCZ,bottleneck,0.000000,False,,1
418,T_CD4_memory,21,21,global,2,68,PRKCZ-AS1,bottleneck,0.000000,False,,1
419,T_CD4_memory,21,21,global,2,69,FAAP20,bottleneck,0.000000,False,,1

# Median bottleneck

In [2]:
import numpy as np
import gudhi as gd
from scipy.optimize import linear_sum_assignment

def _prep(D):
    D = np.asarray(D, float).reshape(-1, 2)
    return D[np.isfinite(D).all(1) & (D[:, 1] > D[:, 0])]

def _linf(A, B):
    return np.maximum(abs(A[:, None, 0] - B[None, :, 0]),
                      abs(A[:, None, 1] - B[None, :, 1]))

def quantile_bottleneck(D, E, q=0.5):
    D, E = _prep(D), _prep(E)
    n, m, N = len(D), len(E), len(D) + len(E)
    if N == 0:
        return 0.0

    dD, dE = (D[:, 1] - D[:, 0]) / 2, (E[:, 1] - E[:, 0]) / 2
    DE = _linf(D, E) if n and m else np.empty((n, m))
    vals = np.unique(np.r_[0, DE.ravel(), dD, dE])
    need = int(np.ceil(q * N))
    BIG = 10**9

    def good_count(t):
        valid = np.zeros((n + m, n + m), bool)
        good = np.zeros((n + m, n + m), int)

        valid[:n, :m] = True
        good[:n, :m] = 2 * (DE <= t)

        valid[np.arange(n), m + np.arange(n)] = True
        good[np.arange(n), m + np.arange(n)] = dD <= t

        valid[n + np.arange(m), np.arange(m)] = True
        good[n + np.arange(m), np.arange(m)] = dE <= t

        valid[n:, m:] = True  # diagonal-to-diagonal fillers

        r, c = linear_sum_assignment(np.where(valid, -good, BIG))
        return good[r, c].sum()

    lo, hi = 0, len(vals) - 1
    while lo < hi:
        mid = (lo + hi) // 2
        if good_count(vals[mid]) >= need:
            hi = mid
        else:
            lo = mid + 1

    return float(vals[lo])

rng = np.random.default_rng(0)

tests = [
    (
        np.array([[0.0, 1.0], [2.0, 3.0]]),
        np.array([[0.1, 1.1], [2.2, 3.1]])
    ),
    (
        np.array([[0.0, 10.0]]),
        np.array([[0.0, 1.0], [2.0, 3.0]])
    ),
    (
        np.empty((0, 2)),
        np.array([[0.0, 1.0], [2.0, 5.0]])
    ),
]

for _ in range(10):
    n, m = rng.integers(0, 8, size=2)
    D = np.c_[rng.uniform(0, 5, n), rng.uniform(5, 10, n)]
    E = np.c_[rng.uniform(0, 5, m), rng.uniform(5, 10, m)]
    tests.append((D, E))

for k, (D, E) in enumerate(tests):
    mine = quantile_bottleneck(D, E, q=1.0)
    gudhi = gd.bottleneck_distance(clean(D), clean(E), e=0)
    med = quantile_bottleneck(D, E, q=0.5)

    print(f"test {k:02d}: mine={mine:.12g}, gudhi={gudhi:.12g}, median={med:.12g}")

    assert np.isclose(mine, gudhi, atol=1e-10), (k, mine, gudhi)

print("All q=1 tests agree with GUDHI bottleneck.")

test 00: mine=0.2, gudhi=0.2, median=0.1
test 01: mine=5, gudhi=5, median=0.5
test 02: mine=1.5, gudhi=1.5, median=0.5
test 03: mine=2.6246679236, gudhi=2.6246679236, median=1.21956550464
test 04: mine=2.09008508061, gudhi=2.09008508061, median=1.24250765738
test 05: mine=2.35966195495, gudhi=2.35966195495, median=1.66525482861
test 06: mine=4.07114605062, gudhi=4.07114605062, median=1.9209556919
test 07: mine=2.613012213, gudhi=2.613012213, median=1.72556253014
test 08: mine=2.40388665404, gudhi=2.40388665404, median=1.5385106196
test 09: mine=4.75184713921, gudhi=4.75184713921, median=2.56486201675
test 10: mine=2.30514059969, gudhi=2.30514059969, median=2.02844245537
test 11: mine=3.24448076951, gudhi=3.24448076951, median=3.24448076951
test 12: mine=2.57542559326, gudhi=2.57542559326, median=1.09786309786
All q=1 tests agree with GUDHI bottleneck.